CREATE TABLE ALUNO(
	ID BIGINT NOT NULL AUTO_INCREMENT,
        NOME_ALUNO VARCHAR(80) NOT NULL,
        RG_ALUNO VARCHAR(15) not null,
	EMAIL_ALUNO VARCHAR(50) not null,
	ENDERECO VARCHAR (100) not null,
    	TELEFONE VARCHAR (15) not null,
     	DIA_VENCIMENTO INT NOT NULL,
	DATA_MATRICULA_ALUNO VARCHAR (10),
	PRIMARY KEY (ID)

 );